general:
  church_suite_org: ''
  production: true

airtable:
  api_key: ''
  base: ''

cache:
  duration_in_seconds: 10

events:
  default_location: 'Church'
  length_in_minutes: 60
  timezone: 'Europe/London'

formats:
  csv_import_datetime: 'd-M-Yg:ia'
  display_date: 'D j M Y'
  display_day: 'D jS'
  display_month: 'F Y'
  display_time: 'H:i'
  ics_date: 'Ymd'
  ics_datetime: 'Ymd\THis'
  json_datetime: 'Y-m-d\TH:i:sO'
  refresh_date: 'd/n'
  prayer_month_id: 'Y-m'
  sortable_date: 'Y-m-d'
  sortable_datetime: 'Y-m-d H:i'

login:
  admin: ''
  api: ''
  max_attempts: 5
  pass: ''

refresh:
  days_before: 7
  days_after: 2

rota:
  bible_version: 'NIVUK'
  default_days: 28
  roles:
    - { name: 'Intercessions', desc: 'Intercessor', abbv: 'I' }
    - { name: 'Preacher', abbv: 'Pr' }
    - { name: 'President', abbv: 'Ps' }
    - { name: 'Readings', desc: 'Reader', abbv: 'R' }
    - { name: 'Service Leader', desc: 'Leader', abbv: 'L' }

prayer:
  day_29: [ '' ]
  day_30: [ '' ]
  day_31: [ '' ]
  show_last_name: true
